# -*- coding: utf-8 -*-
from . import product
from . import sale
from . import is_demande_achat
from . import is_ligne_reception
from . import is_cout
from . import is_taux_change
from . import mrp
from . import is_fiche_tampographie
from . import is_certifications_qualite_suivi
from . import product_pricelist
from . import is_pricelist_item
from . import is_cde_ouverte_fournisseur
from . import account_move
from . import account_move_line
from . import is_edi_cde_cli
from . import is_liste_servir
from . import is_bl_manuel
from . import stock_picking
from . import is_ligne_livraison
from . import mrp_production
from . import is_mrp_production_bom
from . import is_mrp_production_workcenter_line
from . import is_stock_quant
from . import pg_stock_move
from . import stock_move
from . import stock_lot
from . import is_stock_valorise
